version: "3.3"

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --init-file /init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?error}
    volumes:
      - /data/mysql/data:/var/lib/mysql
    networks:
      - proxy
networks:
  proxy:
    external: true
