version: "3.3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=${MYSQL_TZ:-UTC}
    expose:
      - 3306
    environment:
      TZ: ${MYSQL_TZ:-UTC}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?error}
    volumes:
      - /data/mysql/data:/var/lib/mysql
    networks:
      - proxy
networks:
  proxy:
    external: true
