version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - /data/prometheus/data/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/prometheus/data:/prometheus
    networks:
      - proxy # Same network as for Traefik
    labels:
      # Traefik integration labels - start
      - "traefik.enable=true"
      - "traefik.http.services.prometheus.loadBalancer.server.port=9090"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.entrypoints=private-https"
      - "traefik.http.routers.prometheus-secure.rule=Host(`${PROMETHEUS_SERVICE_URL:?error}`)" # e.g. prometheus.example.com
      # Traefik integration labels - end
networks:
  proxy:
    external: true
